<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-22T22:16:46 IST" name="Default suite" finished-at="2025-04-22T22:17:34 IST" duration-ms="48038">
    <groups>
    </groups>
    <test started-at="2025-04-22T22:16:46 IST" name="Default test" finished-at="2025-04-22T22:17:34 IST" duration-ms="48038">
      <class name="Tests.DashboardTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:Tests.DashboardTest@1d296da]" started-at="2025-04-22T22:16:46 IST" name="setup" finished-at="2025-04-22T22:16:57 IST" duration-ms="10701" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login()[pri:0, instance:Tests.DashboardTest@1d296da]" started-at="2025-04-22T22:16:57 IST" name="Login" finished-at="2025-04-22T22:17:19 IST" duration-ms="21778" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method is-config="true" signature="End()[pri:0, instance:Tests.DashboardTest@1d296da]" started-at="2025-04-22T22:17:19 IST" name="End" finished-at="2025-04-22T22:17:20 IST" duration-ms="1238" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- End -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Tests.DashboardTest@1d296da]" started-at="2025-04-22T22:17:20 IST" name="setup" finished-at="2025-04-22T22:17:29 IST" duration-ms="8450" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="QuickLaunch_Assert()[pri:1, instance:Tests.DashboardTest@1d296da]" started-at="2025-04-22T22:17:29 IST" name="QuickLaunch_Assert" finished-at="2025-04-22T22:17:33 IST" duration-ms="4426" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Assign Leave expected:<Assign Leave> but was:<Quick Launch Assertion Failed for: Assign Leave>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Assign Leave expected:<Assign Leave> but was:<Quick Launch Assertion Failed for: Assign Leave>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at Tests.DashboardTest.QuickLaunch_Assert(DashboardTest.java:99)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- QuickLaunch_Assert -->
        <test-method is-config="true" signature="End()[pri:0, instance:Tests.DashboardTest@1d296da]" started-at="2025-04-22T22:17:33 IST" name="End" finished-at="2025-04-22T22:17:34 IST" duration-ms="1375" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- End -->
      </class> <!-- Tests.DashboardTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
